# Generated by Django 2.1.1 on 2019-02-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='tel',
            field=models.CharField(default='', max_length=100),
        ),
    ]
