# Generated by Django 2.1.1 on 2019-03-10 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0003_fruit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='fruit_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Farmer.Fruit'),
        ),
    ]
