# Generated by Django 2.1.1 on 2019-03-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0004_auto_20190310_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='scale',
            field=models.IntegerField(default=''),
        ),
    ]
