# Generated by Django 5.1 on 2026-04-30 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='photo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='planting',
            name='district',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='planting',
            name='province',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='planting',
            name='subdistrict',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='harvest_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
    ]
