# Generated by Django 5.1 on 2026-05-04 18:51

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0002_farmerprofile_photo_planting_district_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruitcrop',
            name='color',
            field=models.CharField(default='#4f8a3d', max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be a hex value such as #4f8a3d.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AlterField(
            model_name='harvestrecord',
            name='price_per_kg',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='harvestrecord',
            name='quantity_kg',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='planting',
            name='area_rai',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddConstraint(
            model_name='farmerprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('phone', ''), _negated=True), fields=('user', 'first_name', 'last_name', 'phone'), name='unique_farmer_identity_with_phone'),
        ),
        migrations.AddConstraint(
            model_name='farmerprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('phone', ''), models.Q(('village', ''), _negated=True)), fields=('user', 'first_name', 'last_name', 'village'), name='unique_farmer_identity_with_village'),
        ),
        migrations.AddConstraint(
            model_name='farmerprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('phone', ''), ('village', '')), fields=('user', 'first_name', 'last_name'), name='unique_farmer_identity_name_only'),
        ),
        migrations.AddConstraint(
            model_name='harvestrecord',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_kg__gte', 0)), name='harvest_quantity_kg_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='harvestrecord',
            constraint=models.CheckConstraint(condition=models.Q(('price_per_kg__gte', 0)), name='harvest_price_per_kg_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='planting',
            constraint=models.UniqueConstraint(fields=('user', 'farmer', 'fruit', 'variety'), name='unique_planting_per_farmer_fruit_variety'),
        ),
        migrations.AddConstraint(
            model_name='planting',
            constraint=models.CheckConstraint(condition=models.Q(('area_rai__gte', 0)), name='planting_area_rai_non_negative'),
        ),
    ]
